name: Android Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Auto Excute And Build APK
      run: |
       cd $GITHUB_WORKSPACE
       chmod +x ~/gradlew
       ./gradlew assembleDebug
    

    - uses: actions/upload-artifact@v3
      with:
        name: ROS
        path: ~/bin/*.apk
